export { default as Accordion } from './accordion'
export { default as Anchor } from './anchor'
export { default as AnimatedSection } from './animated-section'
export { default as Link, type LinkPropeties } from './link'
export { RichText } from './rich-text'
export { StrapiImage, StrapiImageResponsive } from './strapi-image'
export { default as StrapiTitle } from './strapi-title'
export { default as StrapiVideo } from './strapi-video'
